name: abuexpress_app
description: AbuExpress mobile application with onboarding screens
publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.1.0
  rename_app: ^1.6.5
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  audioplayers: ^6.0.0
  url_launcher: ^6.2.5
  http: ^1.2.0
  video_player: ^2.8.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icon/abu-logo.png
    - lib/assets/icon/12abu-logo.png
    - lib/assets/icon/Copy.svg
    - lib/assets/intro/logo.svg
    - lib/assets/intro/box.svg
    - lib/assets/intro/drop.svg
    - lib/assets/intro/world.svg
    - lib/assets/intro.gif
    - lib/assets/intro.mp4
    - assets/audio/airplane_sound.mp3



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icon/abu-logo.png"
  min_sdk_android: 21 
  background_color: "#000000"
  remove_alpha_ios: true
  # Дополнительные параметры для настройки размера:
  # adaptive_icon_background: "#000000"  # Фон для адаптивной иконки Android (8.0+)
  # adaptive_icon_foreground: "lib/assets/icon/abu-logo.png"  # Передний план адаптивной иконки
  # image_path_android: "lib/assets/icon/abu-logo.png"  # Отдельная иконка для Android
  # image_path_ios: "lib/assets/icon/abu-logo.png"  # Отдельная иконка для iOS